setup-fish:
  sed -i -e '/^'"$USER"'/s/\/bin\/bash/\/usr\/bin\/nu/' /etc/passwd
  

setup-fisher:
  fish --command 'curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish | source && fisher install jorgebucaran/fisher'
