setup-fish:
  chsh -s /usr/bin/fish

setup-fisher:
  fish --command 'curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish | source && fisher install jorgebucaran/fisher'